name: tests
on: [pull_request]
jobs:
  test:
    name: awesome-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: awesome-lint
        uses: squadcastHQ/awesome-lint-action@v1.0.1
        continue-on-error: true
      - name: comment PR
        uses: unsplash/comment-on-pr@1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "${{ steps.awesome-lint.outputs.report }}"
