name: tests
on: [pull_request]
jobs:
  test:
    name: awesome-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
          fetch-depth: 0

      - name: Commitlint
        uses: wagoid/commitlint-github-action@v1

      - name: Awesomelint
        id: awesome-lint
        uses: squadcastHQ/awesome-lint-action@v1.0.1

      - name: comment PR
        uses: unsplash/comment-on-pr@v1.2.0
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Report: ${{ steps.awesome-lint.outputs.report }}"
