name: tests
on: [pull_request]
jobs:
  test:
    name: awesome-lint
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Commitlint
        uses: wagoid/commitlint-github-action@v1

      - name: Awesomelint
        id: awesome-lint
        uses: jthegedus/github-action-awesome-lint
